"""Compatibility shim for the reusable ``jsonrpc3`` package."""

from .src.jsonrpc3 import (
    UNSET,
    InboundJSONRPCAbortRequest,
    InboundJSONRPCRequest,
    JSONRPCAck,
    JsonRpcClient,
    JsonRpcClientError,
    JsonRpcConnection,
    JsonRpcContext,
    JSONRPCError,
    JSONRPCErrorCode,
    JsonRpcId,
    JSONRPCMessage,
    JsonRpcProtocolError,
    JSONRPCRequest,
    JSONRPCResponse,
    JsonRpcServer,
    JSONRPCStream,
    JsonRpcStreamCall,
    JsonRpcStreamSink,
    NullJsonRpcStreamSink,
    default_exception_mapper,
    map_exception_type,
    parse_abort_request,
    parse_request,
    rpc_error,
)

__all__ = [
    "JSONRPCErrorCode",
    "JSONRPCAck",
    "JSONRPCError",
    "JSONRPCMessage",
    "JSONRPCRequest",
    "JSONRPCResponse",
    "JSONRPCStream",
    "JsonRpcId",
    "UNSET",
    "InboundJSONRPCAbortRequest",
    "InboundJSONRPCRequest",
    "JsonRpcClient",
    "JsonRpcClientError",
    "JsonRpcStreamCall",
    "JsonRpcConnection",
    "JsonRpcContext",
    "JsonRpcProtocolError",
    "JsonRpcServer",
    "JsonRpcStreamSink",
    "NullJsonRpcStreamSink",
    "default_exception_mapper",
    "map_exception_type",
    "parse_abort_request",
    "parse_request",
    "rpc_error",
]
